# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

# Regras personalizadas
Layout/EmptyLinesAroundClassBody:
  Enabled: true

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/EmptyLinesAroundMethodBody:
  Enabled: true

# Exclui arquivos gerados ou externos
AllCops:
  Exclude:
    - "db/schema.rb"
    - "node_modules/**/*"
    - "bin/**/*"
    - "vendor/**/*"
