name: CI Testes com RSpec

on:
  push:
    branches: [develop]

jobs:
  scan_ruby:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: test_database
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Install dependencies
        run: bundle install --with development test

      - name: Setup DB config
        run: cp config/database.yml.github_actions config/database.yml

      - name: Prepare database
        run: bundle exec rails db:create db:migrate RAILS_ENV=test

      - name: Scan for common Rails security vulnerabilities using static analysis
        run: bin/brakeman --no-pager

      - name: Verificar estilo com RuboCop
        run: bundle exec rubocop

      - name: Rodar testes com RSpec
        run: bundle exec rspec
